const products=[{id:'birthday',name:'Bolo de aniversário',category:'bolos',description:'Para o seu próximo parabéns. Converse sobre sabores e decoração.'},{id:'mousse',name:'Bolo mousse de chocolate',category:'bolos',description:'Chocolate em um dos sabores elogiados por quem já provou.'},{id:'brigadeiro',name:'Brigadeiros',category:'doces',description:'O clássico que faz parte dos melhores momentos.'},{id:'finos',name:'Doces finos',category:'doces',description:'Sabor e apresentação para compor a sua mesa de festa.'}];
const cart=new Map();const dialog=document.querySelector('#cart');const productList=document.querySelector('#products');
productList.innerHTML=products.map((p,i)=>`<article class="product" data-category="${p.category}"><span class="number">0${i+1} / ${p.category==='bolos'?'Bolos':'Doces'}</span><h3>${p.name}</h3><p>${p.description}</p><button data-add="${p.id}">Adicionar à lista <span aria-hidden="true">＋</span></button></article>`).join('');
function updateLink(){
 const selected=products.filter(p=>cart.has(p.id));
 const notes=document.querySelector('#notes').value.trim();
 const lines=['Olá, Gisele! Quero encomendar:'];
 if(selected.length) lines.push(selected.map(p=>`• ${cart.get(p.id)} × ${p.name}`).join('\n'));
 if(notes) lines.push('Detalhes da minha encomenda:\n'+notes);
 lines.push('Você poderia me contar quais sabores e recheios de bolo estão disponíveis? Gostaria de saber também os valores e a disponibilidade para encomenda.','Aguardo seu retorno. Obrigado pelo carinho! 💕');
 document.querySelector('#send-order').href='https://wa.me/5511949449414?text='+encodeURIComponent(lines.join('\n\n'));
}
function renderCart(){document.querySelector('#count').textContent=[...cart.values()].reduce((a,b)=>a+b,0);document.querySelector('#cart-items').innerHTML=cart.size?products.filter(p=>cart.has(p.id)).map(p=>`<div class="cart-row"><strong>${p.name}</strong><div class="qty"><button data-minus="${p.id}" aria-label="Diminuir ${p.name}">−</button><span>${cart.get(p.id)}</span><button data-plus="${p.id}" aria-label="Aumentar ${p.name}">+</button></div></div>`).join(''):'<p class="empty">Sua lista está vazia. Escolha uma delícia no cardápio ou conte sua ideia abaixo.</p>';updateLink();}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelectorAll('.product').forEach(p=>p.hidden=button.dataset.filter!=='all'&&p.dataset.category!==button.dataset.filter);}));
productList.addEventListener('click',e=>{const button=e.target.closest('[data-add]');if(!button)return;const id=button.dataset.add;cart.set(id,(cart.get(id)||0)+1);renderCart();document.querySelector('#announcement').textContent=products.find(p=>p.id===id).name+' adicionado à lista';button.innerHTML='Adicionado à lista <span aria-hidden="true">✓</span>';setTimeout(()=>button.innerHTML='Adicionar à lista <span aria-hidden="true">＋</span>',1400);});
document.querySelector('#open-order').addEventListener('click',()=>{renderCart();dialog.showModal();});document.querySelector('#close-order').addEventListener('click',()=>dialog.close());document.querySelector('#cart-items').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.plus||b.dataset.minus;const n=cart.get(id)+(b.dataset.plus?1:-1);n>0?cart.set(id,n):cart.delete(id);renderCart();});document.querySelector('#notes').addEventListener('input',updateLink);renderCart();
